build:
  image: default-bionic
  environment:
    node:
      version: v16
    php:
      version: 8.2
    hosts:
      testcraft.test: '127.0.0.1'
    variables:
      DB_DSN: 'mysql:host=127.0.0.1;port=3306;dbname=test'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_SCHEMA: ''
      DB_TABLE_PREFIX: ''
      SECURITY_KEY: '12345'
      DEFAULT_SITE_URL: 'http://test.local/'
      XDEBUG_MODE: 'coverage'
  cache:
    directories:
      - node_modules/
      - vendor/
      - ~/.composer/cache/
  dependencies:
    before:
      - mysql -uroot -h 127.0.0.1 -e 'CREATE DATABASE test'
      - cp .github/craft/.env.mysql .env
      - cp .github/craft/craft craft
      - cp .github/craft/bootstrap.php bootstrap.php
  nodes:
    analysis:
      services:
        mysql: 8.0
      project_setup:
        override:
          - true
      tests:
        override:
          - php-scrutinizer-run
          - js-scrutinizer-run
    tests:
      services:
        mysql: 8.0
      project_setup:
        override:
          - true
      tests:
        override:
          - command: 'composer test'
checks:
  php: true
  javascript: true
coding_style:
  php: { }
filter:
  excluded_paths:
    - '*/dist/*'
    - '*/lib/*'
